plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.sevenam.pancakedashboard'
    compileSdk 35

    defaultConfig {
        applicationId 'vn.sevenam.pancakedashboard'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
